# Generated by Django 5.2.3 on 2025-07-21 06:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default='class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='The Sky-infinit School ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='announcement_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_links', to='app_Admin.announcement')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcment_classroom_links', to='app_Admin.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='tragetClass',
            field=models.ManyToManyField(related_name='announcement_targets', through='app_Admin.announcement_class', to='app_Admin.classroom'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('email', models.EmailField(default='@', max_length=254, unique=True)),
                ('contact_no', models.CharField(default='XXXXXXXXXXX', max_length=11)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('classroom', models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='app_Admin.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subj_links', to='app_Admin.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_stu_links', to='app_Admin.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='subject_of_studentt', through='app_Admin.Student_Subject', to='app_Admin.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Join_date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('LEAVE', 'leave')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.teacher'),
        ),
        migrations.CreateModel(
            name='Teacher_classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_teacher_links', to='app_Admin.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classroom_links', to='app_Admin.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(related_name='classroom_of_teachers', through='app_Admin.Teacher_classroom', to='app_Admin.classroom'),
        ),
        migrations.CreateModel(
            name='Teacher_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teach_links', to='app_Admin.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_stu_links', to='app_Admin.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teach_links', to='app_Admin.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sub_links', to='app_Admin.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='subject_of_teachers', through='app_Admin.Teacher_Subject', to='app_Admin.subject'),
        ),
    ]
