# Generated by Django 5.2.3 on 2025-08-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
